[[farmer]]
name = "ordinary"
amount = [1]
energy = 5
efficiency = [8]

[[farmer.requirements]]
    name = "food"
    amount = [1]
    growth = [1]

[[farmer]]
name = "apprentice"
amount = [0]
energy = 2
efficiency = [1]

[[farmer.requirements]]
    name = "food"
    amount = [5]
    growth = [2]
